spring:  
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    # password: '{cipher}10e598f6a019c4d2501dc3c1c1109da6ed244e57673ac93891020d05ca1475a4'
    password: '{cipher}AQANwkKBaE0MbYNsW+QB1TDkwPmVTXF1/S7KgerErLhcbE3BRG8rIYKwFp+8e0W27R/uauVrYgyM/GLsPIRYeb5dZIOt+fAiQQhpr/3fx4zuKqgvNs+Ur6OSn18UzQKyp+bYRFOViLmPU8N9pRQ/PREmHyz7igrGmY9PlJkc1ffGD2Nd6oHNpotam0mABvD0eJ7mAdWqaj9EY4jwpf0WnTsmSB/A9k7Su97Rfvi6N9qwXWChedlfU+eFw8LIDpSV1DBFzL68S9zduui20XydquJeYmgTh7WM8Mhi+NrpDGrQvInUM7F8TstSXSiyHTe4Lg+uTbJZmuUOEP9XAs3PC2mlBKH5cbTqU8vy5m2PdJuDCUIN89K6+w5pstgnckpv2AI='

token:
  expiration_time: 86400000
  # secret: important_key_dev2
  secret: '{cipher}AQBrG5oAZyM94w+EYrCctCNsWJzGXZJPyU2XcZ84cWdHmzpTsgLTUtpGs4QUTQ5Dd4T1PIHz0osAKfF5Wl9l3uh5GD4Dvxku8UcSw5fBB5+nLV0zws1zv0kydYMj7CNCpsq9aL5ft0J80EMRUmCgGAXkoFeES9Sfn6nqacxH8w+cbKbiIaJto2/47IWhclqAwclgoZfe75yaVf4DxyVM+Rr3wb3EtvNxBZqqhOKWE0bvuV0Mnp6a4sT89hFHGzxgu4SbtFUbjvbTJ3BnhsxFHbtMaLzb9ardMPUzQ/3Rl7fLIhhfPCd99Rt7IDu9qSYTcUsp+VEsknMT8p/M9l85yAjLThw0R/CKqMYlKdIxmeC5q+Czjfm2ofQDFU+fllPtoFt+9PXcsjnS03i9KjT9j3IQ'

gateway:
  ip: 127.0.0.1

order-service:
  url: http://127.0.0.1:8000/order/%s/orders